version: "3"
services:
  web:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - default

  app:
    image: node:12
    env_file: ./app.env
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - default
    depends_on:
      - mysql
networks:
  default:
volumes:
  mysqldata:
