export default Object.freeze({
  MIN_HOST_PIECE: 1,
  MAX_HOST_PIECE: 5,
  MIN_GUEST_PIECE: 6,
  MAX_GUEST_PIECE: 10,
  HOLE_NUM: 11,
  TOTAL_BOARD_NUM: 25,
  DROPED_HOST_PIECE: 25,
  DROPED_GUEST_PIECE: 26,
});
